name: auto-release

on:
  push:
    branches:
      - master

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        # Check if 'do-not-release' label set, skip if so. Used for auto-update 'exports/context.tf' version pinning.
        if: "!contains(steps.get-merged-pull-request.outputs.labels, 'do-not-release')"
        with:
          # TODO: set to true when will be sure it works as needed
          publish: false
          prerelease: false
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
